### ISSUE TITLE
Version 3 Tracking Issue

### ISSUE THREAD

**Issue by broofa** [broofa/mime#251]
* [x] Remove Travis CI
* [x] Use GH Actions for CI
* [x] Support ESM imports (#241, #233)
* [x] Convert codebase to Typescript / ESM
* [x] Remove support for `define()` on default instance (see #267)

**Comment by jimmywarting** [comment]
👍  for ESM! 
Would like to just directly import it from a CDN like jsdeliver that have http2 support already and can then be lazy loaded when needed with async import

**Comment by jimmywarting** [comment]
Are u okey with me sending a PR for some ESM?

**Comment by broofa** [comment]
Closing.  `mime@4` (now in `beta`) has all the thingz.

<image src="https://media.giphy.com/media/d30rnjrGa9H1ceGc/giphy-downsized.gif" />
